### ISSUE TITLE
Add YAML build to sourcecontrol

### ISSUE THREAD

**Issue by Jandev** [jfversluis/CfpExchange#79]
Now that we're using Azure DevOps, we can extract the YAML build & release and push it to source control.
This way every contributor can set up their build- & release environment exactly like the maintainers of the project.

**Comment by jfversluis** [comment]
How would you want to use this?

Just static YAML files in a subfolder for you to use? I see also the possibility to create an automatic CI pipeline based on a specially named YAML file. Not too familiar with them myself yet.

**Comment by Jandev** [comment]
Yup, somewhere in the `Deployment` folder, or some other folder for that matter.

Last week @faniereynders mentioned YAML builds in VSTS and I just read some stuff about it for a course I'm preparing. Looks like static files indeed which you can export from an existing pipeline and import from a file. Continuous-integration-as-code!

Also makes it easier to add additional steps if 'someone' wants to add new stuff to the overall solution and it would need additional build steps. Saves us writing a complete how-to workflow in a PR 😄 

BTW: I'm not familiar with it either, yet!

**Comment by jfversluis** [comment]
Yeah really like the idea! I know why you would want it. But didn't really work with it yet 🙂 

But a quick Google action taught me that you can also add a `.vsts-ci.yml` file which automatically provides you with a pipeline in ~VSTS~ ADO. More info: https://blogs.msdn.microsoft.com/devops/2017/11/15/pipeline-as-code-yaml-preview/

Anyway, I'll export the definitions I have now and will put them in the `Deployment` folder. We'll evolve from there.

**Comment by SebastianSchuetze** [comment]
@jfversluis I can take this up! I got somewhat familiar with YAML. I would suggest recreating the pipeline you have into a YAML build.

Would that be okay? Then I would just fork and start a topic branch on it.

**Comment by jfversluis** [comment]
Hi @SebastianSchuetze sorry for the delay! Some personal developments that needed my attention :)

That would definitely be OK! Thank you so much.
It might be worth to wait a little on #109 which brings in a lot of framework updates. That might affect the pipeline. If I can assist you in any way, please let me know!

**Comment by SebastianSchuetze** [comment]
@jfversluis It would probably help if you could give me your pipeline exported as JSON. Don't worry variables marked as secrets properly are not exported. But it would help with the configuration of the tasks. Then you don't need to screenshot them or anything.

**Comment by jfversluis** [comment]
Here you go!

[[master] CI.txt](https://github.com/jfversluis/CfpExchange/files/4067389/master.CI.txt)

**Comment by SebastianSchuetze** [comment]
@jfversluis I am currently going through the pipeline, since the last PR is submitted.

You have some problems there. ;-)

The following things do not work or are not supported:

* All projects are using .net core except the Model project. The unit testing within pipelines cannot handle this very well.
* No unit test are executed within the pipeline
* no code coverage is published
* the publish symbols do not working with GitHub based source code
* you are using mostly msbuild, but it is better to use only the .net core CLI
* you are not at least validating the ARM templates in the builds.

But I am close to fixing this. Here is a public log of the pipeline:
https://dev.azure.com/razorspoint/GitHub_CfPExchange/_build?definitionId=28&_a=summary

it is based on JSON still. After I got it working, I will put it into a YAML pipeline and create a PR.

**Comment by jfversluis** [comment]
This also done. Just evolving from here.
